@startuml Spray-Tek Weather Forecast

class Hyperparameter{
    self.ROOTPATH
    self.DROP_COL
    self.YEILD_THRESHOLD
}

class ImportData{
    __init__()
    import_data()
    read_csv()
}

main->read_csv
read_csv->clean_data
clean_data->missing_plot
missing_plot->drop_na







' A -> B: Hello

' class Hyperparameter{
'     self.path
'     self.yeild
'     ..stings..
'     methodOne()
'     #Public
'     -Private
'     +dfasdf
'     ~dddd   
' }




' class ImportData{
'     int aSceare
'     void startice()
' }
' note left: this is \na secscretClkass

' Myclass <|--- SecondClass


' secdond <...left........rightClass

@enduml